'use client'
import { useState } from "react"
import Link from "next/link"
import { usePathname } from "next/navigation"
import './style.css'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const navLinks = [
  {name: 'Register', href: "/register"},
  {name: 'login', href: '/login'},
  {name: 'forgot password', href: '/forgotpassword'}
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [input, setInput] = useState('')
  const pathname = usePathname()
  return (
    <div>
      {navLinks.map((link) => {
        const isActive = pathname.startsWith(link.href)
        return (
          <Link href={link.href} key={link.name} className={isActive ? "font-bold mr-4" : "text-blue-500 mr-4"}>{link.name}</Link>
        )
      })}
                <div>
          <input value={input} onChange={(e) => setInput(e.target.value)} />
          </div>
    </div>
  )
}
