import { Metadata } from 'next'
import Header from './components/header'
import Footer from './components/footer'


export const metadata : Metadata = {
  title: {
    default: "Next.js - Ismail Muhammed",
    template: "%s | Ismail Muhammed"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Header />
        {children}
        <Footer />
        </body>

    </html>
  )
}
